"""
email_sender.py — Send HTML report email with embedded chart via smtplib.

Configuration via .env file:
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, EMAIL_TO
"""
import smtplib
import os
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from pathlib import Path

log = logging.getLogger(__name__)

# Load from environment (set in .env or OS env)
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
EMAIL_TO  = os.environ.get("EMAIL_TO", "")


def _build_html(summary_html, report_date, anomaly_count):
    anomaly_badge = (
        f'<span style="color:#ff4d4f">⚠️ {anomaly_count} anomalies detected</span>'
        if anomaly_count > 0
        else '<span style="color:#00e5c3">✅ No anomalies</span>'
    )
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;background:#0d1117;color:#e6edf3;padding:32px;margin:0">
  <div style="max-width:700px;margin:0 auto">

    <div style="border-bottom:1px solid #30363d;padding-bottom:16px;margin-bottom:24px">
      <h2 style="color:#00e5c3;margin:0">📊 Daily Telecom Report</h2>
      <p style="color:#8b949e;margin:4px 0 0">{report_date} &nbsp;·&nbsp; Auto-generated by Python Pipeline</p>
    </div>

    <p style="color:#8b949e;font-size:13px">
      Status: {anomaly_badge}
    </p>

    <h3 style="color:#e6edf3;font-size:14px;margin-bottom:8px">Latest Day Summary — Voice SLI Duration</h3>
    {summary_html}

    <div style="margin-top:24px">
      <p style="color:#8b949e;font-size:12px;margin-bottom:8px">Daily Trend (90 days):</p>
      <img src="cid:chart_main" style="width:100%;border-radius:8px;display:block">
    </div>

    <div style="margin-top:32px;border-top:1px solid #21262d;padding-top:16px">
      <p style="color:#484f58;font-size:11px;margin:0">
        Auto-generated · Python Pipeline · Runs daily 06:12 WIB · No manual trigger required
      </p>
    </div>

  </div>
</body>
</html>"""


def send_report(chart_path, summary_html, report_date, anomaly_count=0):
    """
    Send HTML email report with embedded chart image.

    Parameters
    ----------
    chart_path    : str  path to the .jpg chart file
    summary_html  : str  HTML table with operator summary
    report_date   : str  date string for subject/header (YYYY-MM-DD)
    anomaly_count : int  number of anomalies detected
    """
    if not SMTP_USER or not EMAIL_TO:
        log.warning("[email_sender] SMTP_USER or EMAIL_TO not configured — skipping email.")
        return

    msg = MIMEMultipart("related")
    msg["Subject"] = f"[Auto Report] Telecom Daily Summary — {report_date}"
    msg["From"]    = f"Report Bot <{SMTP_USER}>"
    msg["To"]      = EMAIL_TO

    html_body = _build_html(summary_html, report_date, anomaly_count)
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    with open(chart_path, "rb") as f:
        img = MIMEImage(f.read(), _subtype="jpeg")
        img.add_header("Content-ID", "<chart_main>")
        img.add_header("Content-Disposition", "inline", filename="chart.jpg")
        msg.attach(img)

    recipients = [e.strip() for e in EMAIL_TO.split(",") if e.strip()]

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, recipients, msg.as_string())

    log.info("[email_sender] Report sent to: %s", EMAIL_TO)
    print(f"[email_sender] Report sent to {EMAIL_TO}")
